language: java
dist: trusty
jdk:
  - openjdk8


addons:
  sonarcloud:
    organization: "sguiochon"
    token:
  secure: "RsU5C2VUc1lJOkhw9I5KmaaJ4VhWvWBy9dVY6+NzURSA00BwZsmeFjm62RbjDtJTdT015JwQyrSAELOcYrvmrhelzLnJj87BrNmbRagCPJ4Ps08kz6OBKe3Qx14jY181oM6KgH14xoFM2zPHAbth3t2XFeOaNRuX6QeiN/hdEDAikmLOoBlyaoJmBeS91ZUAOsGa7lKFswD2eAJuHEpi7NwT4EGC6I6GFXZhhSdqJaFDlBS8zRr1RjikmTNz/Z7uQ7S33Ua2dOM9HvEDwGD9ZkMm0rvbx4pbjY/XpCnmxOvNiO8EPKW4I478zNTfw3DmJwY1Kyaxf+CN5RGqMrGetOiZw+zQxfR66uwi5fIWWiU9bnw2UliQbPE7hzyvUtdm4Ha+ZcBKwU3BUonV4HbGZkXNAg13nCag5Mnh+Ul9RO+/Xwe7elZTTyaouosIHWQOm22spn8y6BeLLByulH/fRHaw17dXHnk00dghVJ87Vu1mJcBjRCC0TocDn2KUlMpHiNW8PqTayazvWkgVM2MFewNG1dFZExP4kT+DVYzUH1mIu2hte5Zd8BgC0prsm4LpXj1W9fpvDFqc9jU0CbbJm/X6cL9XK0zHrWummkP7JpwfkYEsYVpYqvBamdYEPxD6cpqlyQVzoSyqLnlWXzd8hBqBhVa/gRLbvNfg6p+IC7o="
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=sguiochon_OCRP9