language: java

jdk:
  - openjdk8


addons:
      sonarcloud:
        organization: "sguiochon"
        token:
          secure: "hsavOq+MXWG+Ezb0xyC69H6l9RcxwHQd8hhcnyXaXl2JbPK4wBHHPjysKaqmPisMldRkmRcFlAYL3MHPAqRqzcMsvMc1kGrqWnknm4FqTWFRg65Wz5IM1oP5gnQaEo7zkEW1FntiNXsG40vENftvX4Z2Q1Mf9P+h+gdDnMOcvDx7C0S4iE81lJTRY6s0rDgKAn2cax8jCAEX9OuW16st41tEVLGmuACPimo6ES8/AOXEpXHHmpr6IFDOBdzXNsmTwKacCtqmi7HJynhfKuhcuFt4ZX0AsRsQEJHvt1tOG0xezqcsc73dxsNZhwYmnDlvGMed75TgOeNUSvUAb6l2ACno+e2lcGSQq+TcylHpLgEiCjwSUBSBc0dyZmfqhypqQsZW3AgWqq9DfFIpelJ0XOBzMUXxtKXkcQ0sxqoC0/suaU6a4uc3W9LKIOwGVujW7aIV7ygGipmszLWNl/kNKZx35m35Uy6LKqd1e9oGDR+aLr2HQJOPj4YsK93Diozxu92J7+Fu+vxA9uXGkSFHo1VeEZH7Ka1bHV2kSbqlpZNX9UyVGtmyqUP9SIyRcdGb5c2G1+/9qYAwz6dyAaF5dDvMKAE8u/r+cvWlqEIWYITNWe7baXCqgZDXGVs/nc/JCJRZoTfkZj8xajus10WmWVoTMmFho6cylFnK2/6E4+Q="

script:
      # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
      - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=sguiochon_OCRP9