language: java

jdk:
  - openjdk8


addons:
      sonarcloud:
        organization: "sguiochon"
        token:
          secure: "PtbjQkXi1Pcbll4HX69eVG5cKF1KhHP/OsPMF/6Xw5oLcFJwKh0xUQpIxV5PLbeml0TcgnaIx1BrHLjoNrG8xcUCTuUc5vsu2XL+43qFHwevlq0FtCLpxvNgrFoNVehqkYmLTz9GCKjXEzup5IJ/diLcAvrnpVOFJWka3AEne+JrYGdoajAQ+UtLthk7uJc1H47DddvET+Bp4euBe0J8gr3ykZMekGpp1EMBGzdShsylRtRBH24S4medgJmb8ZWnw0wz5J4kd8KK1cv08VnCa6IFoC9CJK3LS3brzC5oq8k2f5IuiV0Xw+RTrdzbmSP+lPnZXvLGiMsdnzpQEH0Q2qffI6p4eJ5bEU403cfUlS3T7w/Q41705DF/wgBISx+eiCdafcwqoIufxFz8T7NgOtD8vN3heWfQvIVxcVE5+cclQmjwyoVs92oDGVEbaXU6T6NTpo1dckMU6w9ZuMmBr74U3M/j5UYEymIx47gBHAlhB1iO+AYELrigz/v4pbmP1quC01S5ohNZNBn9344QzDu/BKccSux3X//RucEzk9bZA7VpVviv5tzLKK/cTtdIXQmMX+JyrK92u67QULR+gG42btKbb8sE0wxtfJIc38vwmBHzDB2ZGgThI0SUnLlWcO90mE5AP1ppthVZ4yqGQkn7CE+uoW+aQWingkXvM8c="
          
script:
      # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
      - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=sguiochon_OCRP9